### ISSUE TITLE
can't find name $ 

### ISSUE THREAD

**Issue by PraveenYadavADL** [FabianGosebrink/ASPNETCore-Angular-Webpack-StarterTemplate#1]
can't find name $

**Comment by FabianGosebrink** [comment]
Hey @PraveenYadavADL ,

come on, help me out a bit :) what did you do? What is the issue? How did you get to it?

BR

Fabian

**Comment by gouravsinglaadl** [comment]
The issue was because the jquery typings was not installed. I just installed @types/jquery and its resolved and jquery was working fine.
