### ISSUE TITLE
Current Webpack Css Loader Config doesn't handle StyleUrls in Components

### ISSUE THREAD

**Issue by rafaelcgdf** [FabianGosebrink/ASPNETCore-Angular-Webpack-StarterTemplate#5]
I'm trying to follow this webpack configuration in a different App but it's failing due to use of StyleUrls in our components.

I've cloned this repo and tried to add a StyleUrl in the HomeComponent and the result is the same, the App fails to load, screenshots to explain better:

I have tried several different configurations with CSS loaders without any luck, anyone can help me with this issue?

![image](https://user-images.githubusercontent.com/22292601/30321691-d6f17ae2-97ae-11e7-92f0-dd63682c418a.png)

![image](https://user-images.githubusercontent.com/22292601/30321577-7a39847a-97ae-11e7-8f19-d0f0c1f86f39.png)

**Comment by FabianGosebrink** [comment]
Yes, this is a known issue. I will investigate when I have time. I think this can be solved using a tostring-loader. BR

**Comment by rafaelcgdf** [comment]
I've managed to get it "working" with the to-string-loader, but with two problems:

1. It embeds the css into the app.js (no separated bundle css file) 
2. Bootstrap stops being loaded since there's no bundled css (added a CDN in the index for the moment)

`{ 
                test: /\.css$/,
                 use: [ 'to-string-loader', 'css-loader'] 
  }`

I'm going to try to add bootstrap separately into the entry points of webpack, see if that generates something different.

**Comment by FabianGosebrink** [comment]
I think this is the style-loader. For dev its better to not have a seperated *.css file as its faster. For Production this should be extracted. There is the extractTextPlugin doing exactly that. BR

**Comment by rafaelcgdf** [comment]
This is what I have in my webpack.prod.js:

`{
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                })
            }`

If I leave dev with the same config I have the problem in the issue.
Any ideas how I could set bootstrap on dev without the CDN?

**Comment by FabianGosebrink** [comment]
Bootstrap is included in the vendor.ts file https://github.com/FabianGosebrink/ASPNETCore-Angular-Webpack-StarterTemplate/blob/master/src/ASPNETCoreAngularWebpackStarter/angularApp/vendor.ts

**Comment by rafaelcgdf** [comment]
When I use the below config for dev the vendor.css is not created, even tough I've imported bootstrap in the vendor.ts, for production it creates fine but then again I'm using different css configs for dev and prod.

`{ test: /\.css$/, use: [ 'to-string-loader', 'css-loader'] }`

**Comment by FabianGosebrink** [comment]
Are you using the extract-webpack-plugin for dev?

**Comment by rafaelcgdf** [comment]
Is this `ExtractTextPlugin.extract` ?

Not calling that at the moment on dev, should I? 
I think I try to use the `to-string-loader` in there before and it didn't work, I will try again.

**Comment by FabianGosebrink** [comment]
The ExtractTextPlugin is doing a seperate file for you css. If you want a sep file you should use that. Remember: Webpack wants to put all includes in _one_ file. If you want extract one, you got to "say" it. :)

**Comment by rafaelcgdf** [comment]
Just tried several configs, only the one below the build doesn't fail. When trying to open the app I still have the same error that I initially described in the issue

`{
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "to-string-loader",
                    use: ["css-loader"]
                })
            }`

I'm out of ideas :(

**Comment by FabianGosebrink** [comment]
will investigate soon :)

**Comment by FabianGosebrink** [comment]
Does the latest commit help?

**Comment by rafaelcgdf** [comment]
Dev Build is now working using the configuration from the last commit, only problem is that is excluding the styles/custom.css (is probably doing that to yours too).

I will leave that one for dev for the moment, it's good enough without the custom css.
For prod build I will continue using the config that I posted earlier, it works pretty well (includes the custom.css)

Thank you
